using System.Text.Json.Serialization;

namespace SaltyMilky.Net;

/// <summary>
/// Source-generated JSON metadata for NativeAOT-sensitive Milky SDK internals.
/// </summary>
[JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(MilkyApiResponseRaw))]
[JsonSerializable(typeof(MilkyBotOfflineEventData))]
[JsonSerializable(typeof(MilkyCommonEventData))]
[JsonSerializable(typeof(MilkyCookiesResult))]
[JsonSerializable(typeof(MilkyCreateGroupFolderResult))]
[JsonSerializable(typeof(MilkyCsrfTokenResult))]
[JsonSerializable(typeof(MilkyEmptyObject))]
[JsonSerializable(typeof(MilkyEvent))]
[JsonSerializable(typeof(MilkyEventData))]
[JsonSerializable(typeof(MilkyFaceSegment))]
[JsonSerializable(typeof(MilkyFileDownloadUrlResult))]
[JsonSerializable(typeof(MilkyFileIncomingSegment))]
[JsonSerializable(typeof(MilkyFileUploadResult))]
[JsonSerializable(typeof(MilkyForwardedMessagesResult))]
[JsonSerializable(typeof(MilkyForwardSegment))]
[JsonSerializable(typeof(MilkyFriendCategoryEntity))]
[JsonSerializable(typeof(MilkyFriendEntity))]
[JsonSerializable(typeof(MilkyFriendRequest))]
[JsonSerializable(typeof(MilkyFriendRequestsResult))]
[JsonSerializable(typeof(MilkyFriendResult))]
[JsonSerializable(typeof(MilkyFriendsResult))]
[JsonSerializable(typeof(MilkyGetMessageResult))]
[JsonSerializable(typeof(MilkyGroupAnnouncementEntity))]
[JsonSerializable(typeof(MilkyGroupAnnouncementsResult))]
[JsonSerializable(typeof(MilkyGroupEntity))]
[JsonSerializable(typeof(MilkyGroupEssenceMessage))]
[JsonSerializable(typeof(MilkyGroupEssenceMessagesResult))]
[JsonSerializable(typeof(MilkyGroupFileEntity))]
[JsonSerializable(typeof(MilkyGroupFilesResult))]
[JsonSerializable(typeof(MilkyGroupFolderEntity))]
[JsonSerializable(typeof(MilkyGroupMemberEntity))]
[JsonSerializable(typeof(MilkyGroupNotification))]
[JsonSerializable(typeof(MilkyGroupNotificationsResult))]
[JsonSerializable(typeof(MilkyGroupResult))]
[JsonSerializable(typeof(MilkyGroupsResult))]
[JsonSerializable(typeof(MilkyHistoryMessagesResult))]
[JsonSerializable(typeof(MilkyImageSegment))]
[JsonSerializable(typeof(MilkyImplInfoResult))]
[JsonSerializable(typeof(MilkyIncomingFaceSegment))]
[JsonSerializable(typeof(MilkyIncomingForwardedMessage))]
[JsonSerializable(typeof(MilkyIncomingForwardSegment))]
[JsonSerializable(typeof(MilkyIncomingImageSegment))]
[JsonSerializable(typeof(MilkyIncomingLightAppSegment))]
[JsonSerializable(typeof(MilkyIncomingMentionAllSegment))]
[JsonSerializable(typeof(MilkyIncomingMentionSegment))]
[JsonSerializable(typeof(MilkyIncomingMessage))]
[JsonSerializable(typeof(MilkyIncomingRecordSegment))]
[JsonSerializable(typeof(MilkyIncomingReplySegment))]
[JsonSerializable(typeof(MilkyIncomingSegment))]
[JsonSerializable(typeof(MilkyIncomingTextSegment))]
[JsonSerializable(typeof(MilkyIncomingVideoSegment))]
[JsonSerializable(typeof(MilkyLightAppSegment))]
[JsonSerializable(typeof(MilkyLoginInfoResult))]
[JsonSerializable(typeof(MilkyMarketFaceIncomingSegment))]
[JsonSerializable(typeof(MilkyMemberResult))]
[JsonSerializable(typeof(MilkyMembersResult))]
[JsonSerializable(typeof(MilkyMentionAllSegment))]
[JsonSerializable(typeof(MilkyMentionSegment))]
[JsonSerializable(typeof(MilkyMessageRecallEventData))]
[JsonSerializable(typeof(MilkyMessageReceiveEventData))]
[JsonSerializable(typeof(MilkyOutgoingForwardedMessage))]
[JsonSerializable(typeof(MilkyOutgoingSegment))]
[JsonSerializable(typeof(MilkyPeerPinsResult))]
[JsonSerializable(typeof(MilkyRecordSegment))]
[JsonSerializable(typeof(MilkyReplySegment))]
[JsonSerializable(typeof(MilkyResourceTempUrlResult))]
[JsonSerializable(typeof(MilkySendMessageResult))]
[JsonSerializable(typeof(MilkyStringListResult))]
[JsonSerializable(typeof(MilkyTextSegment))]
[JsonSerializable(typeof(MilkyUnknownEventData))]
[JsonSerializable(typeof(MilkyUnknownIncomingSegment))]
[JsonSerializable(typeof(MilkyUserProfileResult))]
[JsonSerializable(typeof(MilkyVideoSegment))]
[JsonSerializable(typeof(MilkyXmlIncomingSegment))]
internal partial class MilkyJsonSerializerContext : JsonSerializerContext
{
}
